#!/usr/bin/env bash
# =============================================================================
# exim_troubleshoot_v3.sh — Read-Only Exim Mail Diagnostic Report for cPanel/WHM
# =============================================================================
# Usage:
#   curl -s https://raw.githubusercontent.com/Exa-Server-team/exim-troubleshoot/main/exim_troubleshoot_v3.sh | sudo bash
#   curl -s https://raw.githubusercontent.com/Exa-Server-team/exim-troubleshoot/main/exim_troubleshoot_v3.sh | sudo bash -s -- --domain example.com
#   curl -s https://raw.githubusercontent.com/Exa-Server-team/exim-troubleshoot/main/exim_troubleshoot_v3.sh | sudo bash -s -- --with-msp
#
# Scope:
#   READ-ONLY diagnostics only.
#   No service restart, no queue deletion, no account suspension, no config changes.
#
# Output:
#   Technical log        : /var/log/exim_troubleshoot_v3_TIMESTAMP.log
#   Client-ready report  : /root/exim_mail_report_v3_TIMESTAMP.txt
# =============================================================================

set -o pipefail

SCRIPT_VERSION="3.0.0"
QUEUE_WARN_THRESHOLD=200
QUEUE_MODERATE_THRESHOLD=50
LOG_SAMPLE_LINES=500

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

pass()  { echo -e "  ${GREEN}[PASS]${RESET} $*"; }
fail()  { echo -e "  ${RED}[FAIL]${RESET} $*"; }
warn()  { echo -e "  ${YELLOW}[WARN]${RESET} $*"; }
info()  { echo -e "  ${CYAN}[INFO]${RESET} $*"; }
hdr()   { echo -e "\n${BOLD}${CYAN}══ $* ══${RESET}"; }
sep()   { echo -e "${CYAN}────────────────────────────────────────────────────${RESET}"; }

cmd_exists() { command -v "$1" >/dev/null 2>&1; }

# ── Root check ───────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo -e "${RED}ERROR:${RESET} This script must be run as root. Try: sudo bash exim_troubleshoot_v3.sh"
  exit 1
fi

# ── Args ─────────────────────────────────────────────────────────────────────
WITH_MSP=0
CHECK_DOMAIN=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --with-msp)
      WITH_MSP=1
      shift
      ;;
    --domain)
      CHECK_DOMAIN="${2:-}"
      shift 2
      ;;
    --help|-h)
      cat <<USAGE
Usage: sudo bash exim_troubleshoot_v3.sh [options]

Options:
  --domain example.com   Optional domain context for report
  --with-msp             Run cPanel MSP RBL/auth scans where available
  --help                 Show this help

This script is read-only and does not modify services, queue, accounts, or config.
USAGE
      exit 0
      ;;
    *)
      warn "Unknown option ignored: $1"
      shift
      ;;
  esac
done

# ── Output files ─────────────────────────────────────────────────────────────
TS=$(date +%Y%m%d_%H%M%S)
TECH_LOG="/var/log/exim_troubleshoot_v3_${TS}.log"
REPORT_FILE="/root/exim_mail_report_v3_${TS}.txt"
TMP_DIR=$(mktemp -d /tmp/exim_v3_XXXXXX)
trap 'rm -rf "$TMP_DIR"' EXIT

exec > >(tee -a "$TECH_LOG") 2>&1

# ── Result storage ───────────────────────────────────────────────────────────
PASS_COUNT=0
WARN_COUNT=0
FAIL_COUNT=0
CLIENT_RESULTS=""
ENGINEER_NOTES=""
SUMMARY_NOTES=""

add_result() {
  local status="$1"
  local title="$2"
  local details="$3"
  local recommend="$4"

  case "$status" in
    PASS) PASS_COUNT=$((PASS_COUNT+1)) ;;
    WARN) WARN_COUNT=$((WARN_COUNT+1)) ;;
    FAIL) FAIL_COUNT=$((FAIL_COUNT+1)) ;;
    INFO) ;;
    *) status="INFO" ;;
  esac

  CLIENT_RESULTS+="${status}|${title}|${details}|${recommend}"$'\n'
}

add_engineer_note() {
  ENGINEER_NOTES+="$*"$'\n'
}

add_summary_note() {
  SUMMARY_NOTES+="- $*"$'\n'
}

write_report() {
  local overall
  if [[ "$FAIL_COUNT" -gt 0 ]]; then
    overall="FAIL"
  elif [[ "$WARN_COUNT" -gt 0 ]]; then
    overall="WARNING"
  else
    overall="PASS"
  fi

  {
    echo "MAIL DELIVERY DIAGNOSTIC REPORT"
    echo "Generated by: Exim Troubleshooter V${SCRIPT_VERSION}"
    echo "Date       : $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo "Server     : ${HOSTNAME:-unknown}"
    echo "Public IP  : ${SERVER_IP:-unknown}"
    [[ -n "$CHECK_DOMAIN" ]] && echo "Domain     : $CHECK_DOMAIN"
    echo "Overall    : $overall"
    echo ""
    echo "EXECUTIVE SUMMARY"
    echo "-----------------"
    if [[ -n "$SUMMARY_NOTES" ]]; then
      echo "$SUMMARY_NOTES"
    else
      echo "- No critical issue was identified from the selected checks."
    fi
    echo ""
    echo "FINDINGS"
    echo "--------"
    while IFS='|' read -r status title details recommend; do
      [[ -z "$status" ]] && continue
      echo "[$status] $title"
      echo "Details       : $details"
      echo "Recommendation: $recommend"
      echo ""
    done <<< "$CLIENT_RESULTS"
    echo "COUNTS"
    echo "------"
    echo "PASS : $PASS_COUNT"
    echo "WARN : $WARN_COUNT"
    echo "FAIL : $FAIL_COUNT"
    echo ""
    echo "ENGINEER NOTES"
    echo "--------------"
    echo "This client report is intentionally summarized. Full technical evidence is saved at:"
    echo "$TECH_LOG"
    echo ""
    if [[ -n "$ENGINEER_NOTES" ]]; then
      echo "$ENGINEER_NOTES"
    else
      echo "No additional engineer notes recorded."
    fi
    echo ""
    echo "IMPORTANT"
    echo "---------"
    echo "This script is read-only. It does not restart services, delete queue messages, suspend accounts, or modify configuration."
  } > "$REPORT_FILE"
}

# =============================================================================
# Banner
# =============================================================================
echo -e "${BOLD}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║      Exim Mail Troubleshooter V3 — cPanel/WHM            ║"
echo "║      READ-ONLY Diagnostic + Client Report Generator      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${RESET}"
info "Script version : $SCRIPT_VERSION"
info "Technical log  : $TECH_LOG"
info "Client report  : $REPORT_FILE"
info "Mode           : READ-ONLY, no automatic fixes"
[[ "$WITH_MSP" -eq 1 ]] && info "MSP scan       : enabled" || info "MSP scan       : skipped by default; use --with-msp"

# =============================================================================
# SECTION 1 — SERVER & EXIM SERVICE
# =============================================================================
hdr "1. Server & Exim Service"
sep

HOSTNAME=$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo "unknown")
SERVER_IP=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || true)
if [[ -z "$SERVER_IP" ]] && cmd_exists dig; then
  SERVER_IP=$(dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null | head -1)
fi
if [[ -z "$SERVER_IP" ]]; then
  SERVER_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") {print $(i+1); exit}}')
fi

info "Hostname  : $HOSTNAME"
info "Public IP : ${SERVER_IP:-unknown}"

if [[ -x /usr/local/cpanel/cpanel ]]; then
  CPANEL_VER=$(/usr/local/cpanel/cpanel -V 2>/dev/null | awk '{print $1}')
  pass "cPanel detected: ${CPANEL_VER:-unknown version}"
  add_result "PASS" "cPanel environment" "cPanel/WHM appears to be installed on this server." "No action required."
else
  warn "cPanel binary not found"
  add_result "WARN" "cPanel environment" "The cPanel binary was not found at /usr/local/cpanel/cpanel." "Engineer should confirm this script is being run on a cPanel/WHM server."
fi

if cmd_exists exim; then
  EXIM_VER=$(exim -bV 2>/dev/null | head -1)
  pass "Exim found: ${EXIM_VER:-version unavailable}"
  add_result "PASS" "Exim binary" "Exim is installed and accessible from the shell." "No action required."
else
  fail "Exim binary not found"
  add_result "FAIL" "Exim binary" "The Exim binary could not be found in PATH." "Engineer should verify whether Exim is installed and whether this is a cPanel mail server."
fi

if systemctl is-active --quiet exim 2>/dev/null || service exim status >/dev/null 2>&1; then
  pass "Exim service is running"
  add_result "PASS" "Exim service" "The Exim mail service is running." "No action required."
else
  fail "Exim service is not running"
  add_result "FAIL" "Exim service" "The Exim mail service does not appear to be running." "Engineer should review Exim service status and Exim panic log before taking action."
  add_summary_note "The Exim mail service may not be running."
fi

# Port checks local
LISTEN_OUTPUT=$(ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null || true)
if echo "$LISTEN_OUTPUT" | grep -Eq '(:|\.)25[[:space:]]'; then
  pass "Port 25 is listening locally"
  add_result "PASS" "SMTP port 25" "The server is listening on SMTP port 25." "No action required."
else
  fail "Port 25 is not listening locally"
  add_result "FAIL" "SMTP port 25" "The server does not appear to be listening on SMTP port 25." "Engineer should verify Exim listener configuration and service status."
  add_summary_note "SMTP port 25 is not detected as listening locally."
fi

if echo "$LISTEN_OUTPUT" | grep -Eq '(:|\.)587[[:space:]]'; then
  pass "Port 587 is listening locally"
  add_result "PASS" "SMTP submission port 587" "The server is listening on SMTP submission port 587." "No action required."
else
  warn "Port 587 is not detected locally"
  add_result "WARN" "SMTP submission port 587" "The server does not appear to be listening on port 587." "Engineer should confirm whether SMTP submission is expected for this server."
fi

# Hostname A and PTR / FCrDNS
if cmd_exists dig && [[ -n "$SERVER_IP" ]]; then
  HOSTNAME_A=$(dig +short "$HOSTNAME" A 2>/dev/null | grep -E '^[0-9.]+' | head -1)
  PTR_RECORD=$(dig +short -x "$SERVER_IP" 2>/dev/null | sed 's/\.$//' | head -1)

  info "Hostname A : ${HOSTNAME_A:-not found}"
  info "PTR record : ${PTR_RECORD:-not found}"

  if [[ -n "$HOSTNAME_A" && "$HOSTNAME_A" == "$SERVER_IP" ]]; then
    pass "Hostname resolves to server public IP"
    add_result "PASS" "Hostname forward DNS" "The hostname resolves to the server public IP." "No action required."
  elif [[ -n "$HOSTNAME_A" ]]; then
    warn "Hostname resolves to $HOSTNAME_A, expected $SERVER_IP"
    add_result "WARN" "Hostname forward DNS" "The hostname resolves to $HOSTNAME_A instead of the detected public IP $SERVER_IP." "Engineer should confirm hostname A record and outbound IP design."
  else
    warn "Hostname A record not found"
    add_result "WARN" "Hostname forward DNS" "No A record was detected for the server hostname." "Add or correct the hostname A record if this server sends mail directly."
  fi

  if [[ -n "$PTR_RECORD" ]]; then
    PTR_A=$(dig +short "$PTR_RECORD" A 2>/dev/null | grep -E '^[0-9.]+' | head -1)
    if [[ "$PTR_A" == "$SERVER_IP" ]]; then
      pass "FCrDNS confirmed: $SERVER_IP -> $PTR_RECORD -> $PTR_A"
      add_result "PASS" "Reverse DNS / FCrDNS" "PTR record exists and resolves back to the server IP." "No action required."
    else
      warn "PTR exists but forward confirmation may not match"
      add_result "WARN" "Reverse DNS / FCrDNS" "PTR is $PTR_RECORD, but its forward A record does not clearly match $SERVER_IP." "Engineer should confirm PTR and forward DNS alignment with the datacenter or IP provider."
    fi
  else
    fail "No PTR record found for $SERVER_IP"
    add_result "FAIL" "Reverse DNS / PTR" "No PTR record was detected for the public IP $SERVER_IP." "Request the datacenter/IP provider to configure PTR to the server hostname."
    add_summary_note "The server public IP does not appear to have a PTR record."
  fi
else
  warn "dig unavailable or public IP unknown; hostname/PTR checks skipped"
  add_result "WARN" "DNS tools" "DNS validation could not be fully completed because dig is unavailable or public IP detection failed." "Install bind-utils/dnsutils or verify network connectivity."
fi

# =============================================================================
# SECTION 2 — MAIL QUEUE STATUS AND SPAM ANALYSIS
# =============================================================================
hdr "2. Mail Queue Status and Spam Analysis"
sep

QUEUE_RAW=""
QUEUE_SIZE=0
if cmd_exists exim; then
  QUEUE_RAW=$(exim -bp 2>/dev/null || true)
  QUEUE_SIZE=$(exim -bpc 2>/dev/null | awk '{print $1}' || echo 0)
  [[ "$QUEUE_SIZE" =~ ^[0-9]+$ ]] || QUEUE_SIZE=$(echo "$QUEUE_RAW" | grep -c '^ *[0-9]')
  info "Messages in queue: $QUEUE_SIZE"

  if [[ "$QUEUE_SIZE" -eq 0 ]]; then
    pass "Mail queue is empty"
    add_result "PASS" "Mail queue" "The Exim mail queue is empty." "No action required."
  elif [[ "$QUEUE_SIZE" -le "$QUEUE_MODERATE_THRESHOLD" ]]; then
    pass "Mail queue is within normal range: $QUEUE_SIZE"
    add_result "PASS" "Mail queue" "The Exim mail queue contains $QUEUE_SIZE message(s), which is within the normal threshold." "No action required."
  elif [[ "$QUEUE_SIZE" -le "$QUEUE_WARN_THRESHOLD" ]]; then
    warn "Mail queue is moderate: $QUEUE_SIZE"
    add_result "WARN" "Mail queue" "The Exim mail queue contains $QUEUE_SIZE message(s), which is elevated but below the high-risk threshold of $QUEUE_WARN_THRESHOLD." "Engineer should monitor queue growth and review recent delivery failures."
    add_summary_note "The mail queue is elevated and should be monitored."
  else
    fail "Mail queue exceeds threshold: $QUEUE_SIZE > $QUEUE_WARN_THRESHOLD"
    add_result "FAIL" "Mail queue" "The Exim mail queue contains $QUEUE_SIZE message(s), exceeding the threshold of $QUEUE_WARN_THRESHOLD." "Engineer should investigate spam source, delivery deferrals, and frozen/bounce messages."
    add_summary_note "The mail queue exceeds the recommended threshold."
  fi

  if [[ "$QUEUE_SIZE" -gt 0 ]]; then
    echo ""
    info "Queue age breakdown:"
    echo "$QUEUE_RAW" | awk '
      /^ *[0-9]+[smhdw]/ {
        raw=$1; age=raw; unit=substr(raw,length(raw),1); sub(/[smhdw]/,"",age)
        if(unit=="s") age=age
        else if(unit=="m") age=age*60
        else if(unit=="h") age=age*3600
        else if(unit=="d") age=age*86400
        else if(unit=="w") age=age*604800
        if(age<3600) lt1h++
        else if(age<86400) lt1d++
        else if(age<604800) lt1w++
        else gt1w++
      }
      END {
        printf "    < 1 hour : %d\n", lt1h+0
        printf "    < 1 day  : %d\n", lt1d+0
        printf "    < 1 week : %d\n", lt1w+0
        printf "    > 1 week : %d\n", gt1w+0
      }'

    FROZEN_COUNT=$(echo "$QUEUE_RAW" | grep -ci 'frozen' || true)
    BOUNCE_COUNT=$(echo "$QUEUE_RAW" | grep -c '<>' || true)
    info "Frozen messages: $FROZEN_COUNT"
    info "Bounce/DSN messages: $BOUNCE_COUNT"

    if [[ "$FROZEN_COUNT" -gt 20 ]]; then
      add_result "WARN" "Frozen queue messages" "$FROZEN_COUNT frozen message(s) were detected in the Exim queue." "Engineer should review frozen messages and confirm whether cleanup is appropriate."
    elif [[ "$FROZEN_COUNT" -gt 0 ]]; then
      add_result "INFO" "Frozen queue messages" "$FROZEN_COUNT frozen message(s) were detected." "Review only if mail delay complaints are reported."
    else
      add_result "PASS" "Frozen queue messages" "No frozen messages were detected in the Exim queue." "No action required."
    fi

    if [[ "$BOUNCE_COUNT" -gt 50 ]]; then
      add_result "WARN" "Bounce/DSN volume" "$BOUNCE_COUNT bounce/DSN message(s) were detected." "Engineer should review whether outbound spam or invalid recipient delivery attempts are generating bounces."
    else
      add_result "PASS" "Bounce/DSN volume" "Bounce/DSN volume is not high based on current queue sample." "No action required."
    fi

    echo ""
    info "Top sender addresses in current queue:"
    TOP_SENDERS=$(echo "$QUEUE_RAW" | sed -n 's/.*<\([^>]*@[^>]*\)>.*/\1/p' | sort | uniq -c | sort -rn | head -10)
    if [[ -n "$TOP_SENDERS" ]]; then
      echo "$TOP_SENDERS" | sed 's/^/    /'
      add_engineer_note "Top queue senders:"$'\n'"$TOP_SENDERS"
      TOP_SENDER_COUNT=$(echo "$TOP_SENDERS" | head -1 | awk '{print $1}')
      TOP_SENDER_ADDR=$(echo "$TOP_SENDERS" | head -1 | awk '{print $2}')
      if [[ "${TOP_SENDER_COUNT:-0}" -gt 50 ]]; then
        add_result "WARN" "Bulk sender pattern" "One sender appears frequently in the queue." "Engineer should review the top sender account for bulk sending, compromise, or application-generated mail."
        add_engineer_note "Possible bulk sender: $TOP_SENDER_ADDR with $TOP_SENDER_COUNT queued messages."
      fi
    else
      info "No sender address summary available from queue output."
    fi
  fi
else
  fail "Cannot run queue checks because Exim is unavailable"
  add_result "FAIL" "Mail queue" "Queue analysis could not be performed because Exim is unavailable." "Engineer should verify Exim installation and service state."
fi

# =============================================================================
# SECTION 3 — FIREWALL & PORT CHECKS
# =============================================================================
hdr "3. Firewall & Port Checks"
sep

# Local SMTP banner test
if cmd_exists nc; then
  SMTP_TEST=$(echo "QUIT" | timeout 5 nc -w 3 127.0.0.1 25 2>/dev/null | head -1)
  if echo "$SMTP_TEST" | grep -q '^220'; then
    pass "Local SMTP banner received: $SMTP_TEST"
    add_result "PASS" "Local SMTP banner" "A valid SMTP banner was received from localhost port 25." "No action required."
  else
    fail "No valid SMTP banner from localhost port 25"
    add_result "FAIL" "Local SMTP banner" "No valid SMTP banner was received from localhost port 25." "Engineer should check Exim listener/service status and local firewall behavior."
    add_summary_note "Local SMTP banner test failed."
  fi
else
  warn "nc not installed; SMTP banner test skipped"
  add_result "WARN" "Local SMTP banner" "The nc command is unavailable, so SMTP banner testing was skipped." "Install nc/nmap-ncat if banner testing is required."
fi

# firewalld
if systemctl is-active --quiet firewalld 2>/dev/null; then
  info "firewalld is active"
  FW_PORTS=$(firewall-cmd --list-ports 2>/dev/null || true)
  FW_SERVICES=$(firewall-cmd --list-services 2>/dev/null || true)
  echo "    Ports   : ${FW_PORTS:-none listed}"
  echo "    Services: ${FW_SERVICES:-none listed}"
  if echo "$FW_PORTS $FW_SERVICES" | grep -Eq '25/tcp|smtp'; then
    pass "SMTP appears allowed in firewalld"
    add_result "PASS" "firewalld SMTP rule" "firewalld is active and SMTP appears to be allowed." "No action required."
  else
    warn "SMTP not clearly allowed in firewalld"
    add_result "WARN" "firewalld SMTP rule" "firewalld is active, but SMTP was not clearly found in listed ports/services." "Engineer should verify firewall policy for inbound SMTP."
  fi
else
  info "firewalld is not active or not installed"
  add_result "INFO" "firewalld" "firewalld is not active or not installed." "No action required if another firewall is used."
fi

# CSF
if [[ -f /etc/csf/csf.conf ]]; then
  info "CSF detected: /etc/csf/csf.conf"
  TCP_IN=$(grep '^TCP_IN' /etc/csf/csf.conf 2>/dev/null | head -1)
  TCP_OUT=$(grep '^TCP_OUT' /etc/csf/csf.conf 2>/dev/null | head -1)
  echo "    $TCP_IN"
  echo "    $TCP_OUT"
  if echo "$TCP_IN" | grep -q '25'; then
    pass "CSF TCP_IN includes port 25"
    add_result "PASS" "CSF inbound SMTP" "CSF TCP_IN includes port 25." "No action required."
  else
    warn "CSF TCP_IN does not clearly include port 25"
    add_result "WARN" "CSF inbound SMTP" "CSF is installed, but TCP_IN does not clearly include port 25." "Engineer should verify whether inbound SMTP should be allowed."
  fi
  if echo "$TCP_OUT" | grep -q '25'; then
    pass "CSF TCP_OUT includes port 25"
    add_result "PASS" "CSF outbound SMTP" "CSF TCP_OUT includes port 25." "No action required."
  else
    warn "CSF TCP_OUT does not clearly include port 25"
    add_result "WARN" "CSF outbound SMTP" "CSF is installed, but TCP_OUT does not clearly include port 25." "Engineer should verify outbound SMTP policy."
  fi
else
  info "CSF not detected"
  add_result "INFO" "CSF firewall" "CSF was not detected on this server." "No action required if another firewall is used."
fi

# iptables summary
if cmd_exists iptables; then
  IPT_SMTP=$(iptables -S 2>/dev/null | grep -E 'dport (25|465|587)|spt (25|465|587)' | head -20 || true)
  if [[ -n "$IPT_SMTP" ]]; then
    info "iptables SMTP-related rules found:"
    echo "$IPT_SMTP" | sed 's/^/    /'
    add_engineer_note "iptables SMTP-related rules detected:"$'\n'"$IPT_SMTP"
  else
    info "No obvious iptables SMTP-specific rules found in sample."
  fi
fi

# =============================================================================
# SECTION 4 — DISK SPACE & MAIL QUOTAS
# =============================================================================
hdr "4. Disk Space & Mail Quotas"
sep

info "Disk usage for key partitions:"
df -h / /home /var /tmp 2>/dev/null | sed 's/^/    /'

FULL_PARTS=$(df -hP 2>/dev/null | awk 'NR>1 && $5+0 >= 90 {print $6 " " $5}')
if [[ -n "$FULL_PARTS" ]]; then
  fail "High disk usage detected"
  echo "$FULL_PARTS" | sed 's/^/    /'
  add_result "FAIL" "Disk usage" "One or more partitions are at or above 90% usage." "Engineer should free disk space before mail service is affected."
  add_summary_note "One or more partitions are critically full."
else
  pass "No partitions at or above 90% usage"
  add_result "PASS" "Disk usage" "No partition was detected at or above 90% usage." "No action required."
fi

if [[ -d /var/spool/exim ]]; then
  SPOOL_SIZE=$(du -sh /var/spool/exim 2>/dev/null | awk '{print $1}')
  info "Exim spool size: ${SPOOL_SIZE:-unknown}"
  add_result "INFO" "Exim spool size" "Current Exim spool size is ${SPOOL_SIZE:-unknown}." "Review if queue size is high or /var usage is elevated."
else
  warn "Exim spool directory not found at /var/spool/exim"
  add_result "WARN" "Exim spool directory" "The Exim spool directory was not found at /var/spool/exim." "Engineer should confirm Exim spool path and installation layout."
fi

if [[ -d /home ]]; then
  info "Top /home user disk usage sample:"
  du -sh /home/* 2>/dev/null | sort -hr | head -10 | sed 's/^/    /'
fi

# Mail quota hints
if [[ -d /home ]]; then
  MAIL_USAGE=$(du -sh /home/*/mail 2>/dev/null | sort -hr | head -10 || true)
  if [[ -n "$MAIL_USAGE" ]]; then
    info "Top mail storage usage under /home/*/mail:"
    echo "$MAIL_USAGE" | sed 's/^/    /'
    add_engineer_note "Top mail storage usage:"$'\n'"$MAIL_USAGE"
    add_result "INFO" "Mailbox storage" "Mailbox storage usage summary was collected for engineer review." "Review large mailboxes if disk usage or quota complaints are reported."
  else
    info "No /home/*/mail usage data available."
  fi
fi

# =============================================================================
# SECTION 5 — OUTGOING MAIL IP / NAT / MAILHELO CHECK
# =============================================================================
hdr "5. Outgoing Mail IP / NAT / Mailhelo Check"
sep

info "Detected public IP: ${SERVER_IP:-unknown}"
info "Kernel route source IP sample:"
ROUTE_SRC=$(ip route get 8.8.8.8 2>/dev/null | tee "$TMP_DIR/ip_route.txt" | awk '{for(i=1;i<=NF;i++) if($i=="src") {print $(i+1); exit}}')
cat "$TMP_DIR/ip_route.txt" 2>/dev/null | sed 's/^/    /'

if [[ -n "$SERVER_IP" && -n "$ROUTE_SRC" && "$SERVER_IP" != "$ROUTE_SRC" ]]; then
  warn "Public IP and route source IP differ: public=$SERVER_IP route_src=$ROUTE_SRC"
  add_result "WARN" "Outgoing IP / NAT" "The detected public IP differs from the local route source IP." "Engineer should confirm NAT, outbound SMTP IP, SPF, and PTR alignment."
  add_summary_note "Detected public IP and route source IP differ, which may indicate NAT or custom outbound routing."
else
  pass "Outgoing IP appears consistent or no NAT mismatch was detected"
  add_result "PASS" "Outgoing IP / NAT" "No obvious mismatch was detected between public IP and route source IP." "No action required."
fi

if [[ -f /etc/mailips ]]; then
  info "/etc/mailips found:"
  sed 's/^/    /' /etc/mailips
  add_engineer_note "/etc/mailips content:"$'\n'"$(cat /etc/mailips 2>/dev/null)"
  add_result "INFO" "cPanel mailips" "/etc/mailips exists, indicating possible custom outbound IP mapping." "Engineer should verify each mapped IP has matching SPF/PTR/rDNS."
else
  info "/etc/mailips not found; default outbound IP behavior likely applies"
  add_result "INFO" "cPanel mailips" "/etc/mailips was not found." "No action required unless custom outbound IP mapping is expected."
fi

if [[ -f /etc/mailhelo ]]; then
  info "/etc/mailhelo found:"
  sed 's/^/    /' /etc/mailhelo
  add_engineer_note "/etc/mailhelo content:"$'\n'"$(cat /etc/mailhelo 2>/dev/null)"
  add_result "INFO" "cPanel mailhelo" "/etc/mailhelo exists, indicating possible custom HELO mapping." "Engineer should verify HELO values align with PTR and hostname policy."
else
  info "/etc/mailhelo not found; default HELO behavior likely applies"
  add_result "INFO" "cPanel mailhelo" "/etc/mailhelo was not found." "No action required unless custom HELO mapping is expected."
fi

if [[ -f /etc/ips ]]; then
  info "Server IP list from /etc/ips:"
  sed 's/^/    /' /etc/ips
  add_engineer_note "/etc/ips content:"$'\n'"$(cat /etc/ips 2>/dev/null)"
fi

if cmd_exists exim; then
  EXIM_INTERFACE=$(exim -bP 2>/dev/null | grep -i '^interface' || true)
  if [[ -n "$EXIM_INTERFACE" ]]; then
    info "Exim interface configuration:"
    echo "$EXIM_INTERFACE" | sed 's/^/    /'
    add_engineer_note "Exim interface configuration:"$'\n'"$EXIM_INTERFACE"
  else
    info "No explicit Exim interface setting detected from exim -bP."
  fi
fi

# =============================================================================
# SECTION 6 — MSP / IP REPUTATION / RBL SCAN
# =============================================================================
hdr "6. MSP / IP Reputation / RBL Scan"
sep

if [[ "$WITH_MSP" -ne 1 ]]; then
  warn "MSP scan skipped by default. Run with --with-msp to enable."
  add_result "INFO" "MSP/RBL scan" "MSP/RBL scan was skipped by default." "Run with --with-msp when reputation or spam-source analysis is required."
else
  if ! cmd_exists curl; then
    fail "curl not found; cannot download MSP"
    add_result "WARN" "MSP/RBL scan" "curl is unavailable, so MSP could not be downloaded." "Install curl or run MSP manually from a trusted source."
  elif [[ ! -x /usr/local/cpanel/3rdparty/bin/perl && ! $(command -v perl 2>/dev/null) ]]; then
    fail "perl not found; cannot run MSP"
    add_result "WARN" "MSP/RBL scan" "Perl is unavailable, so MSP could not be executed." "Install Perl or use cPanel bundled Perl if available."
  else
    CPANEL_PERL="/usr/local/cpanel/3rdparty/bin/perl"
    [[ -x "$CPANEL_PERL" ]] || CPANEL_PERL="$(command -v perl)"
    MSP_URL="https://raw.githubusercontent.com/CpanelInc/tech-MSP/master/msp.pl"
    MSP_TMP="$TMP_DIR/msp.pl"

    info "Downloading MSP from: $MSP_URL"
    if curl -s --max-time 30 "$MSP_URL" -o "$MSP_TMP" && [[ -s "$MSP_TMP" ]]; then
      pass "MSP downloaded"
      echo ""
      info "Running MSP --rbl all. Full output is recorded in technical log."
      MSP_RBL_OUT="$TMP_DIR/msp_rbl.out"
      "$CPANEL_PERL" "$MSP_TMP" --rbl all > "$MSP_RBL_OUT" 2>&1 || true
      sed 's/^/    /' "$MSP_RBL_OUT" | head -200

      if grep -Eiq 'listed|blacklist|rbl.*yes|found.*on' "$MSP_RBL_OUT"; then
        warn "MSP RBL output may indicate one or more reputation concerns"
        add_result "WARN" "MSP RBL scan" "MSP RBL scan completed and may indicate one or more listing/reputation concerns." "Engineer should review the technical log and verify affected IPs with external RBL tools."
        add_summary_note "MSP RBL scan may indicate reputation concerns."
      else
        pass "No obvious RBL listing pattern detected in MSP output"
        add_result "PASS" "MSP RBL scan" "MSP RBL scan completed and no obvious listing pattern was detected in script output." "No action required, but external reputation tools may still be checked for confirmation."
      fi

      echo ""
      info "Running MSP --auth. Full output is recorded in technical log."
      MSP_AUTH_OUT="$TMP_DIR/msp_auth.out"
      "$CPANEL_PERL" "$MSP_TMP" --auth > "$MSP_AUTH_OUT" 2>&1 || true
      sed 's/^/    /' "$MSP_AUTH_OUT" | head -200

      if grep -Eiq 'suspicious|compromised|auth|sent|login|password' "$MSP_AUTH_OUT"; then
        add_result "INFO" "MSP auth scan" "MSP authentication/source scan completed and output was captured for engineer review." "Engineer should review top authenticated senders and confirm whether any account shows abnormal sending behavior."
      else
        add_result "INFO" "MSP auth scan" "MSP authentication/source scan completed with limited or no notable output." "No immediate action required unless queue/log evidence indicates spam."
      fi

      add_engineer_note "MSP --rbl all output saved in technical log. MSP --auth output saved in technical log."
    else
      fail "Failed to download MSP"
      add_result "WARN" "MSP/RBL scan" "MSP could not be downloaded from GitHub." "Engineer should verify internet/GitHub access or run MSP manually."
    fi
  fi
fi

# Reputation web URLs for client/engineer reference
if [[ -n "$SERVER_IP" ]]; then
  add_engineer_note "Reputation check URLs for $SERVER_IP:"$'\n'"- https://multirbl.valli.org/lookup/${SERVER_IP}.html"$'\n'"- https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a${SERVER_IP}"$'\n'"- https://www.talosintelligence.com/reputation_center/lookup?search=${SERVER_IP}"
fi

# =============================================================================
# SECTION 7 — EXIM LOG HEALTH
# =============================================================================
hdr "7. Exim Log Health"
sep

MAINLOG="/var/log/exim_mainlog"
REJECTLOG="/var/log/exim_rejectlog"
PANICLOG="/var/log/exim_paniclog"

if [[ -f "$PANICLOG" ]]; then
  PANIC_LINES=$(grep -cv '^$' "$PANICLOG" 2>/dev/null || echo 0)
  if [[ "$PANIC_LINES" -gt 0 ]]; then
    fail "Exim panic log has entries: $PANIC_LINES"
    tail -50 "$PANICLOG" | sed 's/^/    /'
    add_result "FAIL" "Exim panic log" "The Exim panic log contains $PANIC_LINES non-empty line(s)." "Engineer should review /var/log/exim_paniclog for critical Exim errors."
    add_summary_note "Exim panic log contains entries."
  else
    pass "Exim panic log is empty"
    add_result "PASS" "Exim panic log" "No entries were detected in the Exim panic log." "No action required."
  fi
else
  info "Exim panic log not found at $PANICLOG"
  add_result "INFO" "Exim panic log" "The Exim panic log was not found at the standard path." "No action required if logging path differs on this server."
fi

if [[ -f "$REJECTLOG" ]]; then
  RECENT_REJECTS=$(tail -$LOG_SAMPLE_LINES "$REJECTLOG" 2>/dev/null | grep -ciE 'reject|denied|blocked|failed' || true)
  info "Recent rejection indicators in last $LOG_SAMPLE_LINES rejectlog lines: $RECENT_REJECTS"
  if [[ "$RECENT_REJECTS" -gt 100 ]]; then
    warn "High recent rejection volume detected"
    add_result "WARN" "Exim reject log" "High rejection activity was detected in the recent Exim reject log sample." "Engineer should review whether rejections are caused by spam attacks, invalid recipients, RBLs, or authentication failures."
    add_summary_note "High rejection activity was detected in Exim logs."
  else
    pass "No high rejection volume detected in sample"
    add_result "PASS" "Exim reject log" "No high rejection volume was detected in the recent reject log sample." "No action required."
  fi
  echo ""
  info "Recent reject log sample:"
  tail -10 "$REJECTLOG" 2>/dev/null | sed 's/^/    /'
else
  info "Exim reject log not found at $REJECTLOG"
  add_result "INFO" "Exim reject log" "The Exim reject log was not found at the standard path." "No action required if logging path differs on this server."
fi

if [[ -f "$MAINLOG" ]]; then
  info "Exim mainlog found: $MAINLOG"
  FAIL_SAMPLE=$(tail -$LOG_SAMPLE_LINES "$MAINLOG" 2>/dev/null | grep -ciE 'defer|failed|unrouteable|retry timeout|connection timed out|temporarily rejected' || true)
  info "Recent delivery failure/defer indicators in last $LOG_SAMPLE_LINES mainlog lines: $FAIL_SAMPLE"
  if [[ "$FAIL_SAMPLE" -gt 100 ]]; then
    warn "High recent delivery failure/defer indicators detected"
    add_result "WARN" "Exim mainlog delivery health" "High failure/defer indicators were detected in the recent Exim mainlog sample." "Engineer should review remote rejection, DNS, routing, and queue retry patterns."
    add_summary_note "High delivery failure/defer activity was detected in Exim mainlog."
  else
    pass "No high delivery failure/defer volume detected in sample"
    add_result "PASS" "Exim mainlog delivery health" "No high failure/defer volume was detected in the recent Exim mainlog sample." "No action required."
  fi

  echo ""
  info "Top cwd/script path indicators from recent mainlog sample:"
  CWD_SAMPLE=$(tail -$LOG_SAMPLE_LINES "$MAINLOG" 2>/dev/null | sed -n 's/.*cwd=\([^ ]*\).*/\1/p' | sort | uniq -c | sort -rn | head -10)
  if [[ -n "$CWD_SAMPLE" ]]; then
    echo "$CWD_SAMPLE" | sed 's/^/    /'
    add_engineer_note "Recent cwd/script path indicators:"$'\n'"$CWD_SAMPLE"
  else
    info "No cwd/script path indicators detected in sample."
  fi
else
  warn "Exim mainlog not found at $MAINLOG"
  add_result "WARN" "Exim mainlog" "The Exim mainlog was not found at /var/log/exim_mainlog." "Engineer should confirm Exim log path and logging configuration."
fi

# =============================================================================
# REPORT
# =============================================================================
hdr "Report Generation"
sep
write_report
pass "Troubleshoot run completed"
pass "Technical log saved to: $TECH_LOG"
pass "Client-ready report saved to: $REPORT_FILE"

echo ""
echo -e "${BOLD}${GREEN}Done.${RESET}"
echo ""
